ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.omie.modules.RoutingKt.configureRouting
      - com.omie.modules.BrokerModuleKt.configureMessaging
      - com.omie.modules.ClientModuleKt.configureClients
      - com.omie.modules.InvoiceListenerModuleKt.configureInvoiceListener


omie:
  url: "https://app.omie.com.br/api/v1/financas/contareceber/"
  appKey: "$OMIE_APP_KEY"
  appSecret: "$OMIE_APP_SECRET"

rabbitmq:
  connection:
    host: "$RABBITMQ_HOST:localhost"
    port: "$RABBITMQ_PORT:5672"
    username: "$RABBITMQ_USER:guest"
    password: "$RABBITMQ_PASSWORD:guest"
    virtualHost: "$RABBITMQ_VHOST:/"
  queues:
    input: "$RABBITMQ_QUEUE_INPUT:bowe-dev-lote-conta-receber-omie"
    success: "$RABBITMQ_QUEUE_SUCCESS:bowe-dev-gerar-fatura"
    error: "$RABBITMQ_QUEUE_ERROR:bowe-dev-error-fatura"
  consumer:
    prefetch: "$RABBITMQ_PREFETCH:10"